"""The ratchet: every (provider, property, case) the suite runs that fails on today's trunk, with the failure as
observed, in one line. A listed case is expected to fail, strictly: when it starts passing, the run fails until its
entry is removed, so every fix is recorded here. An unlisted failure fails the run. This table may only shrink.

Regenerated by hand from a run: never add an entry to make a red case green without the line saying what the
provider does wrong."""

from __future__ import annotations

from dataclasses import dataclass

from tests.conformance.contract import Property


@dataclass(frozen=True)
class Known:
    provider: str
    prop: Property
    case: str
    observed: str


KNOWN: tuple[Known, ...] = (
    Known(
        "asana",
        Property.FAMILY,
        "tickets",
        'VendorRefused: link two tasks: 404 {"errors": [{"message": "No matching route for request", "help": "For more information on API status codes and how to handle them, read the docs ',
    ),
    Known(
        "asana",
        Property.IDS,
        "stable_under_additions_and_reordering",
        "in a seed listing one more first, ticket Original one: 1190000000000000 -> 1190000000000001",
    ),
    Known(
        "asana",
        Property.PEOPLE_ACT,
        "act_move_ticket",
        "the API says the change was made by None, not sofia@example.com",
    ),
    Known(
        "asana",
        Property.PEOPLE_ACT,
        "happening_moves_cancelled",
        "the API says the change was made by None, not sofia@example.com",
    ),
    Known(
        "asana",
        Property.PEOPLE_ACT,
        "happening_moves_done",
        "the API says the change was made by None, not sofia@example.com",
    ),
    Known(
        "asana",
        Property.PEOPLE_ACT,
        "happening_reassigns",
        "the API says the change was made by None, not sofia@example.com",
    ),
    Known(
        "asana",
        Property.PEOPLE_ACT,
        "happening_reopens",
        "the API says the change was made by None, not sofia@example.com",
    ),
    Known(
        "asana",
        Property.PEOPLE_ACT,
        "happening_unassigns",
        "the API says the change was made by None, not sofia@example.com",
    ),
    Known(
        "asana",
        Property.RECORD,
        "unknown_credential_refused_and_unclaimed",
        'answered 502 \'{"error": "no world claims this call: none holds its credentials or host", "host": "app.asana.com"}\'; the vendor\'s documented refusal is 401 holding \'Not Authorized\'',
    ),
    Known(
        "asana",
        Property.SEEDED,
        "person_deactivated",
        "'Dee Activated' was seeded deactivated; the vendor lists email=dee@example.com active=True bot=False guest=False title=None",
    ),
    Known(
        "asana",
        Property.SEEDED,
        "person_guest",
        "'Gus Guest' was seeded as a guest; the vendor lists email=gus@example.com active=True bot=False guest=False title=None",
    ),
    Known("asana", Property.SEEDED, "sign_in", "NotImplementedError: AsanaDriver has no sign-in"),
    Known(
        "aws",
        Property.RECORD,
        "unknown_credential_refused_and_unclaimed",
        "answered 200 '{\"Schedules\": [], \"NextToken\": null}'; the vendor's documented refusal is 403 holding 'The security token included in the request is invalid'",
    ),
    Known("aws", Property.SEEDED, "sign_in", "NotImplementedError: AwsDriver has no sign-in"),
    Known(
        "github",
        Property.ACCOUNTS,
        "no_email",
        "the shared seed model cannot declare a no_email account: 1 validation error for CreateWorld",
    ),
    Known(
        "github",
        Property.IDS,
        "documented_format",
        'VendorRefused: list organization members: 501 {"message":"minutehand\'s github fake does not implement GET /orgs/launch-team/members: it is not among the calls this provider serves (its README\'s table)"',
    ),
    Known(
        "github",
        Property.IDS,
        "stable_under_additions_and_reordering",
        'VendorRefused: list organization members: 501 {"message":"minutehand\'s github fake does not implement GET /orgs/launch-team/members: it is not among the calls this provider serves (its README\'s table)"',
    ),
    Known(
        "github",
        Property.LISTING,
        "people",
        'VendorRefused: list organization members: 501 {"message":"minutehand\'s github fake does not implement GET /orgs/launch-team/members: it is not among the calls this provider serves (its README\'s table)"',
    ),
    Known(
        "github",
        Property.RECORD,
        "every_call_kept_once_in_order_verbatim",
        'VendorRefused: list organization members: 501 {"message":"minutehand\'s github fake does not implement GET /orgs/launch-team/members: it is not among the calls this provider serves (its README\'s table)"',
    ),
    Known(
        "github",
        Property.RECORD,
        "unknown_credential_refused_and_unclaimed",
        'answered 502 \'{"error": "no world claims this call: none holds its credentials or host", "host": "api.github.com"}\'; the vendor\'s documented refusal is 401 holding \'Bad credentials',
    ),
    Known(
        "github",
        Property.SEEDED,
        "person_bot",
        'VendorRefused: list organization members: 501 {"message":"minutehand\'s github fake does not implement GET /orgs/launch-team/members: it is not among the calls this provider serves (its README\'s table)"',
    ),
    Known(
        "github",
        Property.SEEDED,
        "person_guest",
        'VendorRefused: list organization members: 501 {"message":"minutehand\'s github fake does not implement GET /orgs/launch-team/members: it is not among the calls this provider serves (its README\'s table)"',
    ),
    Known(
        "github",
        Property.SEEDED,
        "person_name_and_email",
        'VendorRefused: list organization members: 501 {"message":"minutehand\'s github fake does not implement GET /orgs/launch-team/members: it is not among the calls this provider serves (its README\'s table)"',
    ),
    Known(
        "github",
        Property.SEEDED,
        "person_without_email",
        "the shared seed model refused the seed before any provider was asked, naming no provider: 1 validation error for CreateWorld / seed.people.3.email / Field required [type=missing, i",
    ),
    Known("github", Property.SEEDED, "sign_in", "NotImplementedError: GitHubDriver has no sign-in"),
    Known(
        "github",
        Property.STATE,
        "a_world_reopened_answers_as_in_a_fresh_server",
        'VendorRefused: create or update file contents: 501 {"message":"minutehand\'s github fake does not implement PUT /repos/launch-team/notes/contents/…: it is not among the calls this provider serves (its README\'s table)"',
    ),
    Known(
        "github",
        Property.STATE,
        "concurrent_worlds_never_see_each_other",
        '[VendorRefused(\'create or update file contents: 501 {"message":"minutehand\\\'s github fake does not implement PUT /repo...calls this provider serves (its README\\\'s table)","documentation_url":"https://docs.github.com/rest","status":"501"}\')]',
    ),
    Known(
        "github",
        Property.STATE,
        "reset_returns_the_seeded_answers",
        'VendorRefused: create or update file contents: 501 {"message":"minutehand\'s github fake does not implement PUT /repos/launch-team/notes/contents/…: it is not among the calls this provider serves (its README\'s table)"',
    ),
    Known(
        "github",
        Property.TIME,
        "new_things_carry_the_worlds_clock",
        'VendorRefused: create or update file contents: 501 {"message":"minutehand\'s github fake does not implement PUT /repos/launch-team/notes/contents/…: it is not among the calls this provider serves (its README\'s table)"',
    ),
    Known(
        "google_cloud_tasks",
        Property.RECORD,
        "unknown_credential_refused_and_unclaimed",
        'answered 502 \'{"error": "no world claims this call: none holds its credentials or host", "host": "cloudtasks.googleapis.com"}\'; the vendor\'s documented refusal is 401 holding \'Request had invalid authentication credentials\'',
    ),
    Known(
        "google_workspace",
        Property.FAMILY,
        "documents",
        "the document's first neutral change is [('create', {'title': 'My Drive', 'text': '', 'parent': 'None', 'owner': 'owen@example.com', 'space': 'None', 'mime': 'application/vnd.google",
    ),
    Known(
        "google_workspace",
        Property.IDS,
        "stable_under_additions_and_reordering",
        "in a seed listing one more first, document Original doc: 1F00000000000099875f5ee919c73f -> 1F00000000000199875f5ee919c73f",
    ),
    Known("google_workspace", Property.PEOPLE_ACT, "happening_moved", "the API shows the folder None"),
    Known(
        "google_workspace",
        Property.RECORD,
        "every_call_kept_once_in_order_verbatim",
        "call 1 (POST oauth2.googleapis.com/token): the answer kept differs from what was answered (130 bytes)",
    ),
    Known(
        "google_workspace",
        Property.RECORD,
        "unknown_credential_refused_and_unclaimed",
        'answered 502 \'{"error": "no world claims this call: none holds its credentials or host", "host": "www.googleapis.com"}\'; the vendor\'s documented refusal is 401 holding \'Invalid Cre',
    ),
    Known(
        "google_workspace",
        Property.SEEDED,
        "document_file",
        "the world's neutral text of 'Fact document' lacks ['fact,csv']: ''",
    ),
    Known(
        "google_workspace",
        Property.SEEDED,
        "document_folder",
        "seeded in Fact/Nested, the neutral view's parent is None",
    ),
    Known(
        "jira",
        Property.ACCOUNTS,
        "no_email",
        "the shared seed model cannot declare a no_email account: 1 validation error for CreateWorld",
    ),
    Known(
        "jira",
        Property.FAMILY,
        "same_as_asana_tickets",
        'asana cannot complete the lifecycle, so jira cannot be compared with it: link two tasks: 404 {"errors": [{"message": "No matching route for request", "help": "For more information ',
    ),
    Known(
        "jira",
        Property.IDS,
        "stable_under_additions_and_reordering",
        "in a seed listing one more first, ticket Original one: 1000 -> 1001",
    ),
    Known(
        "jira",
        Property.RECORD,
        "unknown_credential_refused_and_unclaimed",
        'answered 401 \'{"errorMessages": ["You are not signed in: this request carries no credentials the site accepts."], "errors": {}}\'; the vendor\'s documented refusal is 401 holding \'Cl',
    ),
    Known(
        "jira",
        Property.SEEDED,
        "person_bot",
        "'Robo Helper' was seeded as a bot; the vendor lists email=robo@example.com active=True bot=False guest=False title=None",
    ),
    Known(
        "jira",
        Property.SEEDED,
        "person_deactivated",
        "'Dee Activated' was seeded deactivated; the vendor lists email=dee@example.com active=True bot=False guest=False title=None",
    ),
    Known(
        "jira",
        Property.SEEDED,
        "person_without_email",
        "the shared seed model refused the seed before any provider was asked, naming no provider: 1 validation error for CreateWorld / seed.people.3.email / Field required [type=missing, i",
    ),
    Known("jira", Property.SEEDED, "sign_in", "NotImplementedError: JiraDriver has no sign-in"),
    Known(
        "jira",
        Property.SEEDED,
        "ticket_title_body_project",
        "the neutral view holds body 'First line, ünïcode.\\nSecond line with <angle brackets> & ampersand.', project 'LAUNCH'; seeded in project 'Launch'",
    ),
    Known(
        "microsoft",
        Property.ACCOUNTS,
        "no_email",
        "the shared seed model cannot declare a no_email account: 1 validation error for Seed",
    ),
    Known(
        "microsoft",
        Property.ACCOUNTS,
        "vendor_login",
        "NotImplementedError: Microsoft accounts have a login of their own (the userPrincipalName), but the Microsoft seed has no field naming one: the provider derives it from the email's ",
    ),
    Known(
        "microsoft",
        Property.FAMILY,
        "documents",
        "the document's first neutral change is [('create', {'title': 'Lifecycle doc.docx', 'text': '', 'parent': 'None', 'owner': 'Agent', 'space': 'C89C8622814 Team', 'mime': 'application",
    ),
    Known(
        "microsoft",
        Property.FAMILY,
        "messages_in_a_channel",
        'VendorRefused: POST /teams/<uuid>/channels/19%3Afd63656c101954db8978628cec4f181c%40thread.tacv2/messages/1788253200000024/setReaction: documented 204, answered: 403 {"error":{"code',
    ),
    Known(
        "microsoft",
        Property.FAMILY,
        "messages_in_a_direct_conversation",
        'VendorRefused: POST /chats/19%3A<uuid>_<uuid>%40unq.gbl.spaces/messages/1788253200000025/setReaction: documented 204, answered: 403 {"error":{"code":"Forbidden","message":"Sending ',
    ),
    Known(
        "microsoft",
        Property.FAMILY,
        "same_as_google_workspace_documents",
        "the neutral sequences part at step 1: microsoft [('agent', 'create', 'document', 'T1', (('title', 'Lifecycle doc.docx'), ('text', ''), ('parent', 'None'), ('owner', 'Agent'), ('spa",
    ),
    Known(
        "microsoft",
        Property.IDS,
        "documented_format",
        "message #launch Original post: '1788246000000001' does not match ^\\d{13}$",
    ),
    Known(
        "microsoft",
        Property.PEOPLE_ACT,
        "act_reply",
        "#talk holds 0 messages 'Sofia answers': ['Seeded root', \"Sofia's own post\", 'The agent asks', 'Agent Sofia answers']",
    ),
    Known(
        "microsoft",
        Property.PEOPLE_ACT,
        "happening_opens_agent",
        "refused without naming microsoft: Teams pushes nothing to a bot when a person opens its app; this happening has no Teams form",
    ),
    Known("microsoft", Property.PEOPLE_ACT, "happening_reacts", "the API shows the reactions ()"),
    Known(
        "microsoft", Property.PEOPLE_ACT, "happening_shared", "shared mila commenter: {'mila@example.com': 'reader'}"
    ),
    Known(
        "microsoft",
        Property.RECORD,
        "every_call_kept_once_in_order_verbatim",
        'VendorRefused: GET /servicePrincipals(appId=\'<uuid>\'): 400 {"error":{"code":"BadRequest","message":"Resource not found for the segment \'servicePrincipals(appId=\'<uuid>\')\'.","innerE',
    ),
    Known(
        "microsoft",
        Property.RECORD,
        "unknown_credential_refused_and_unclaimed",
        'answered 502 \'{"error": "no world claims this call: none holds its credentials or host", "host": "graph.microsoft.com"}\'; the vendor\'s documented refusal is 401 holding \'InvalidAut',
    ),
    Known(
        "microsoft",
        Property.SEEDED,
        "channel_archived",
        "fact-channel was seeded archived; the API shows private=False archived=False topic='' purpose='', ['owen@example.com', 'sofia@example.com']",
    ),
    Known(
        "microsoft",
        Property.SEEDED,
        "channel_private",
        "fact-channel was seeded private; the API shows private=False archived=False topic='' purpose='', ['owen@example.com', 'sofia@example.com']",
    ),
    Known(
        "microsoft",
        Property.SEEDED,
        "channel_purpose",
        "fact-channel was seeded with a purpose; the API shows private=False archived=False topic='' purpose='', ['owen@example.com', 'sofia@example.com']",
    ),
    Known(
        "microsoft",
        Property.SEEDED,
        "document_file",
        "'Fact document' was seeded a file; the API shows a document (application/vnd.openxmlformats-officedocument.wordprocessingml.document)",
    ),
    Known(
        "microsoft",
        Property.SEEDED,
        "document_folder",
        "the world's neutral view holds 0 documents titled 'Fact document'",
    ),
    Known(
        "microsoft",
        Property.SEEDED,
        "document_last_editor",
        "seeded last changed by mila 3 days before the start; the API: None at 2026-09-01 09:00:00+00:00",
    ),
    Known("microsoft", Property.SEEDED, "document_owner", "seeded owned by sofia, the API shows owner None"),
    Known(
        "microsoft",
        Property.SEEDED,
        "document_presentation",
        "'Fact document' was seeded a presentation; the API shows a document (application/vnd.openxmlformats-officedocument.wordprocessingml.document)",
    ),
    Known("microsoft", Property.SEEDED, "document_sharing", "seeded mila commenter; the API: {}"),
    Known(
        "microsoft",
        Property.SEEDED,
        "document_spreadsheet",
        "'Fact document' was seeded a spreadsheet; the API shows a document (application/vnd.openxmlformats-officedocument.wordprocessingml.document)",
    ),
    Known(
        "microsoft",
        Property.SEEDED,
        "document_text",
        "the world's neutral view holds 0 documents titled 'Fact document'",
    ),
    Known(
        "microsoft",
        Property.SEEDED,
        "person_deactivated",
        "'Dee Activated' was seeded deactivated; the vendor lists email=dee@example.com active=True bot=False guest=False title=None",
    ),
    Known(
        "microsoft",
        Property.SEEDED,
        "person_guest",
        "'Gus Guest' was seeded as a guest; the vendor lists email=gus@example.com active=True bot=False guest=False title=None",
    ),
    Known(
        "microsoft",
        Property.SEEDED,
        "person_without_email",
        "the shared seed model refused the seed before any provider was asked, naming no provider: 1 validation error for Seed / people.3.email / Field required [type=missing, input_value={",
    ),
    Known("microsoft", Property.SEEDED, "sign_in", "NotImplementedError: MicrosoftDriver has no sign-in"),
    Known(
        "notion",
        Property.FAMILY,
        "documents",
        'VendorRefused: move a page: 400 {"object": "error", "status": 400, "code": "invalid_request_url", "message": "There is no endpoint at this path.", "request_id": "<uuid>"}',
    ),
    Known(
        "notion",
        Property.FAMILY,
        "same_as_google_workspace_documents",
        'VendorRefused: move a page: 400 {"object": "error", "status": 400, "code": "invalid_request_url", "message": "There is no endpoint at this path.", "request_id": "<uuid>"}',
    ),
    Known(
        "notion",
        Property.IDS,
        "stable_under_additions_and_reordering",
        "in a seed listing one more first, document Original doc: <uuid> -> <uuid>",
    ),
    Known(
        "notion",
        Property.PEOPLE_ACT,
        "happening_field_set",
        "refused without naming notion: <uuid> is a page, not a row of a database, so it has no 'Status' to set",
    ),
    Known(
        "notion",
        Property.RECORD,
        "binary_upload_and_download",
        'VendorRefused: create a file upload: 400 {"object": "error", "status": 400, "code": "invalid_request_url", "message": "There is no endpoint at this path.", "request_id": "<uuid>"}',
    ),
    Known(
        "notion",
        Property.RECORD,
        "unknown_credential_refused_and_unclaimed",
        'answered 502 \'{"error": "no world claims this call: none holds its credentials or host", "host": "api.notion.com"}\'; the vendor\'s documented refusal is 401 holding \'unauthorized\'',
    ),
    Known(
        "notion",
        Property.SEEDED,
        "document_folder",
        "seeded in Fact/Nested, the neutral view's parent is 'Fact/Nested'",
    ),
    Known(
        "notion",
        Property.SEEDED,
        "document_last_editor",
        "seeded last changed by mila 3 days before the start; the API: owen@example.com at 2026-09-01 09:00:00+00:00",
    ),
    Known("notion", Property.SEEDED, "document_owner", "seeded owned by sofia, the API shows owner owen@example.com"),
    Known(
        "notion",
        Property.SEEDED,
        "person_bot",
        "'Robo Helper' was seeded as a bot; the vendor lists email=robo@example.com active=True bot=False guest=False title=None",
    ),
    Known("notion", Property.SEEDED, "sign_in", "NotImplementedError: NotionDriver has no sign-in"),
    Known(
        "notion",
        Property.TIME,
        "new_things_carry_the_worlds_clock",
        "advancing the clock changed what the vendor answers for what was there",
    ),
    Known(
        "slack",
        Property.ACCOUNTS,
        "bot",
        'SlackRefused: conversations.open: cannot_dm_bot (200 {"ok":false,"error":"cannot_dm_bot"})',
    ),
    Known("slack", Property.ACCOUNTS, "member", "signs in: AssertionError signed in as ava, answered as 'agent'"),
    Known(
        "slack",
        Property.ACCOUNTS,
        "no_email",
        "the shared seed model cannot declare a no_email account: 1 validation error for Seed",
    ),
    Known(
        "slack",
        Property.FAMILY,
        "same_as_microsoft_messages_in_a_channel",
        "microsoft cannot complete the lifecycle, so slack cannot be compared with it: POST /teams/<uuid>/channels/19%3Ac741879c406c5172ac0c440396e8ffbb%40thread.tacv2/messages/178825320000",
    ),
    Known(
        "slack",
        Property.FAMILY,
        "same_as_microsoft_messages_in_a_direct_conversation",
        "microsoft cannot complete the lifecycle, so slack cannot be compared with it: POST /chats/19%3A<uuid>_<uuid>%40unq.gbl.spaces/messages/1788253200000025/setReaction: documented 204,",
    ),
    Known(
        "slack",
        Property.RECORD,
        "unknown_credential_refused_and_unclaimed",
        'answered 502 \'{"error": "no world claims this call: none holds its credentials or host", "host": "slack.com"}\'; the vendor\'s documented refusal is 200 holding \'invalid_auth\'',
    ),
    Known(
        "slack",
        Property.SEEDED,
        "person_without_email",
        "the shared seed model refused the seed before any provider was asked, naming no provider: 1 validation error for Seed / people.3.email / Field required [type=missing, input_value={",
    ),
    Known("slack", Property.SEEDED, "sign_in", "the sign-in seeded for sofia answers as 'agent'"),
    Known(
        "youtrack",
        Property.ACCOUNTS,
        "no_email",
        "the shared seed model cannot declare a no_email account: 1 validation error for Seed",
    ),
    Known(
        "youtrack",
        Property.ACCOUNTS,
        "vendor_login",
        "NotImplementedError: the youtrack seed gives each scenario person the login of their Person.key and has no field that gives a person another login, so {'lena': 'Lena.Ortiz-QA'} can",
    ),
    Known(
        "youtrack",
        Property.FAMILY,
        "same_as_asana_tickets",
        'asana cannot complete the lifecycle, so youtrack cannot be compared with it: link two tasks: 404 {"errors": [{"message": "No matching route for request", "help": "For more informat',
    ),
    Known(
        "youtrack",
        Property.IDS,
        "stable_under_additions_and_reordering",
        "in a seed listing one more first, person mila@example.com: 1-3 -> 1-4",
    ),
    Known(
        "youtrack",
        Property.RECORD,
        "unknown_credential_refused_and_unclaimed",
        "the call is not in the unclaimed list: []",
    ),
    Known(
        "youtrack",
        Property.SEEDED,
        "person_deactivated",
        "'Dee Activated' was seeded deactivated; the vendor lists email=dee@example.com active=True bot=False guest=False title=None",
    ),
    Known(
        "youtrack",
        Property.SEEDED,
        "person_without_email",
        "the shared seed model refused the seed before any provider was asked, naming no provider: 1 validation error for Seed / people.3.email / Field required [type=missing, input_value={",
    ),
    Known("youtrack", Property.SEEDED, "sign_in", "NotImplementedError: YouTrackDriver has no sign-in"),
    Known(
        "youtrack",
        Property.SEEDED,
        "ticket_title_body_project",
        "the neutral view holds body 'First line, ünïcode.\\nSecond line with <angle brackets> & ampersand.', project 'LAUNCH'; seeded in project 'Launch'",
    ),
)
