"""What the Slack provider claims. Data only: nothing else in the provider is imported to read it."""

from __future__ import annotations

from minutehand.domain.provider import (
    Holds,
    Manifest,
    Tier,
)
from minutehand.domain.world import EntityKind

MANIFEST = Manifest(
    key="slack",
    tier=Tier.FINISHED,
    hosts=["slack.com", "*.slack.com"],
    kinds=[EntityKind.MESSAGE, EntityKind.CHANNEL],
    pushes_events=True,
    holds=Holds(
        person_without_email=True,
        person_title=True,
        person_guest=True,
        person_deactivated=True,
        person_bot=True,
        person_working_hours=True,
        person_absences=True,
        account_login=False,
        account_id=True,
        account_name=True,
        account_email_hidden=True,
        ticket_key=False,
        ticket_labels=False,
        ticket_comments=False,
        ticket_number=False,
        ticket_id=False,
        document_spreadsheet=False,
        document_presentation=False,
        document_file=False,
        document_folder=False,
        document_owner=False,
        document_space=False,
        document_shared_with=False,
        document_modified_before_start=False,
        document_modified_by=False,
        document_id=False,
        channel_named=True,
        channel_direct=True,
        channel_private=True,
        channel_archived=True,
        channel_topic=True,
        channel_purpose=True,
        channel_without_agent=True,
        channel_history=True,
        channel_threads=True,
        channel_files=True,
        channel_id=True,
        channel_post_id=True,
        space_spaces=False,
        space_id=False,
        ticket_action_moves=False,
        ticket_action_reassigns=False,
        ticket_action_comments=False,
        ticket_action_deletes=False,
        messaging_posts=True,
        messaging_edits=True,
        messaging_deletes=True,
        messaging_reacts=True,
        messaging_joins=True,
        messaging_adds_agent=True,
        messaging_opens_agent=True,
        messaging_commands=True,
        document_change_edited=False,
        document_change_renamed=False,
        document_change_moved=False,
        document_change_shared=False,
        document_change_trashed=False,
        document_change_commented=False,
        document_change_field_set=False,
        people_change_removed=False,
        people_change_deactivated=True,
        people_change_reactivated=True,
        sign_ins=True,
        faults=True,
    ),
)
