"""Notion's API surface, as data: every operation of its published OpenAPI document
(https://developers.notion.com/openapi.json, describing version 2026-03-11, retrieved 2026-10-08), and the one operation of
2022-06-28 that document no longer lists (`POST /v1/databases/{database_id}/query`,
https://developers.notion.com/reference/post-database-query). The app serves some and answers every other one 501
naming it (`app.UNSERVED`), so no endpoint Notion has is answered as if it had none."""

from __future__ import annotations

OPERATIONS: tuple[tuple[str, str, str], ...] = (
    ("POST", "/v1/agents/batch", "agent-batch"),
    ("POST", "/v1/agents/query", "query-agents"),
    ("DELETE", "/v1/agents/{agent_id}", "delete-agent"),
    ("GET", "/v1/agents/{agent_id}", "get-agent"),
    ("PATCH", "/v1/agents/{agent_id}/credit_limit", "update-agent-credit-limit"),
    ("GET", "/v1/agents/{agent_id}/insights", "get-agent-insights"),
    ("PATCH", "/v1/agents/{agent_id}/status", "update-agent-status"),
    ("GET", "/v1/ai/plugins", "list-skills-plugins"),
    ("GET", "/v1/ai/plugins/{id}", "get-plugin-directory"),
    ("GET", "/v1/ai/skills/{id}", "get-skill-directory"),
    ("GET", "/v1/async_tasks/{task_id}", "retrieve-async-task"),
    ("POST", "/v1/blocks/meeting_notes", "create-meeting-note"),
    ("POST", "/v1/blocks/meeting_notes/query", "query-meeting-notes"),
    ("DELETE", "/v1/blocks/{block_id}", "delete-a-block"),
    ("GET", "/v1/blocks/{block_id}", "retrieve-a-block"),
    ("PATCH", "/v1/blocks/{block_id}", "update-a-block"),
    ("GET", "/v1/blocks/{block_id}/children", "get-block-children"),
    ("PATCH", "/v1/blocks/{block_id}/children", "patch-block-children"),
    ("GET", "/v1/comments", "list-comments"),
    ("POST", "/v1/comments", "create-a-comment"),
    ("DELETE", "/v1/comments/{comment_id}", "delete-a-comment"),
    ("GET", "/v1/comments/{comment_id}", "retrieve-comment"),
    ("PATCH", "/v1/comments/{comment_id}", "update-a-comment"),
    ("GET", "/v1/custom_emojis", "list-custom-emojis"),
    ("POST", "/v1/data_sources", "create-a-database"),
    ("GET", "/v1/data_sources/{data_source_id}", "retrieve-a-data-source"),
    ("PATCH", "/v1/data_sources/{data_source_id}", "update-a-data-source"),
    ("POST", "/v1/data_sources/{data_source_id}/query", "post-database-query"),
    ("GET", "/v1/data_sources/{data_source_id}/templates", "list-data-source-templates"),
    ("POST", "/v1/databases", "create-database"),
    ("GET", "/v1/databases/{database_id}", "retrieve-database"),
    ("PATCH", "/v1/databases/{database_id}", "update-database"),
    ("POST", "/v1/databases/{database_id}/query", "post-database-query"),
    ("GET", "/v1/file_uploads", "list-file-uploads"),
    ("POST", "/v1/file_uploads", "create-file"),
    ("GET", "/v1/file_uploads/{file_upload_id}", "retrieve-file-upload"),
    ("POST", "/v1/file_uploads/{file_upload_id}/complete", "complete-file-upload"),
    ("POST", "/v1/file_uploads/{file_upload_id}/send", "upload-file"),
    ("POST", "/v1/oauth/introspect", "introspect-token"),
    ("POST", "/v1/oauth/revoke", "revoke-token"),
    ("POST", "/v1/oauth/token", "create-a-token"),
    ("POST", "/v1/pages", "post-page"),
    ("GET", "/v1/pages/{page_id}", "retrieve-a-page"),
    ("PATCH", "/v1/pages/{page_id}", "patch-page"),
    ("GET", "/v1/pages/{page_id}/markdown", "retrieve-page-markdown"),
    ("PATCH", "/v1/pages/{page_id}/markdown", "update-page-markdown"),
    ("POST", "/v1/pages/{page_id}/move", "move-page"),
    ("GET", "/v1/pages/{page_id}/properties/{property_id}", "retrieve-a-page-property"),
    ("POST", "/v1/search", "post-search"),
    ("POST", "/v1/sessions", "update-session"),
    ("POST", "/v1/sessions/query", "query-sessions"),
    ("GET", "/v1/sessions/{session_id}", "retrieve-session"),
    ("POST", "/v1/sessions/{session_id}/cancel", "cancel-session"),
    ("POST", "/v1/sessions/{session_id}/events/query", "query-session-events"),
    ("GET", "/v1/users", "get-users"),
    ("GET", "/v1/users/me", "get-self"),
    ("GET", "/v1/users/{user_id}", "get-user"),
    ("GET", "/v1/views", "list-views"),
    ("POST", "/v1/views", "create-view"),
    ("DELETE", "/v1/views/{view_id}", "delete-view"),
    ("GET", "/v1/views/{view_id}", "retrieve-a-view"),
    ("PATCH", "/v1/views/{view_id}", "update-a-view"),
    ("POST", "/v1/views/{view_id}/queries", "create-view-query"),
    ("DELETE", "/v1/views/{view_id}/queries/{query_id}", "delete-view-query"),
    ("GET", "/v1/views/{view_id}/queries/{query_id}", "get-view-query-results"),
)
"""Method, path and operationId of every operation, in path order."""
