"""What the Google Drive provider claims. Data only: nothing else in the provider is imported to read it."""

from __future__ import annotations

from minutehand.domain.provider import (
    Holds,
    Manifest,
    Tier,
)
from minutehand.domain.world import EntityKind

MANIFEST = Manifest(
    key="google_drive",
    tier=Tier.FINISHED,
    hosts=[
        "www.googleapis.com",
        "oauth2.googleapis.com",
        "docs.googleapis.com",
        "slides.googleapis.com",
        "iamcredentials.googleapis.com",
    ],
    kinds=[EntityKind.DOCUMENT, EntityKind.COMMENT],
    holds=Holds(
        person_without_email=True,
        person_title=False,
        person_guest=False,
        person_deactivated=False,
        person_bot=False,
        person_working_hours=False,
        person_absences=False,
        account_login=False,
        account_id=True,
        account_name=True,
        account_email_hidden=True,
        ticket_key=False,
        ticket_labels=False,
        ticket_comments=False,
        ticket_number=False,
        ticket_id=False,
        document_spreadsheet=True,
        document_presentation=True,
        document_file=True,
        document_folder=True,
        document_owner=True,
        document_space=True,
        document_shared_with=True,
        document_modified_before_start=True,
        document_modified_by=True,
        document_id=True,
        channel_named=False,
        channel_direct=False,
        channel_private=False,
        channel_archived=False,
        channel_topic=False,
        channel_purpose=False,
        channel_without_agent=False,
        channel_history=False,
        channel_threads=False,
        channel_files=False,
        channel_id=False,
        channel_post_id=False,
        space_spaces=True,
        space_id=True,
        ticket_action_moves=False,
        ticket_action_reassigns=False,
        ticket_action_comments=False,
        ticket_action_deletes=False,
        messaging_posts=False,
        messaging_edits=False,
        messaging_deletes=False,
        messaging_reacts=False,
        messaging_joins=False,
        messaging_adds_agent=False,
        messaging_opens_agent=False,
        messaging_commands=False,
        document_change_edited=True,
        document_change_renamed=True,
        document_change_moved=True,
        document_change_shared=True,
        document_change_trashed=True,
        document_change_commented=True,
        document_change_field_set=False,
        people_change_removed=False,
        people_change_deactivated=False,
        people_change_reactivated=False,
        sign_ins=True,
        faults=True,
    ),
)
