"""What Jira Cloud's reference lists for the resources this fake claims, and this fake does not serve.

The resources are those `tests/data/vendor_surface/jira.json` holds: the platform v3 OpenAPI description
(https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json) and the Agile one
(https://developer.atlassian.com/cloud/jira/software/swagger.v3.json), cut to issues, comments, search and JQL,
users, projects, worklogs, attachments, issue links, the site objects served, boards and sprints, as fetched on
2026-10-08. Each operation below is refused by name: the app raises `NotImplementedError`, which the proxy answers
501 in Jira's error body naming the method and this path. Any other operation of the subset has a handler in
`app.py`; `tests/providers/jira/test_jira_surface.py` holds the two lists to the subset, and the subset to the
spec it was cut from.
"""

from __future__ import annotations

UNSERVED: dict[str, tuple[str, ...]] = {
    "/rest/agile/1.0/board": ("POST",),
    "/rest/agile/1.0/board/{boardId}": ("DELETE", "GET"),
    "/rest/agile/1.0/board/{boardId}/sprint/{sprintId}/issue": ("GET",),
    "/rest/agile/1.0/sprint": ("POST",),
    "/rest/agile/1.0/sprint/{sprintId}": ("DELETE", "GET", "POST", "PUT"),
    "/rest/agile/1.0/sprint/{sprintId}/issue": ("GET",),
    "/rest/agile/1.0/sprint/{sprintId}/properties": ("GET",),
    "/rest/agile/1.0/sprint/{sprintId}/properties/{propertyKey}": ("DELETE", "GET", "PUT"),
    "/rest/agile/1.0/sprint/{sprintId}/swap": ("POST",),
    "/rest/api/3/attachment/content/{id}": ("GET",),
    "/rest/api/3/attachment/meta": ("GET",),
    "/rest/api/3/attachment/thumbnail/{id}": ("GET",),
    "/rest/api/3/attachment/{id}": ("DELETE", "GET"),
    "/rest/api/3/attachment/{id}/expand/human": ("GET",),
    "/rest/api/3/attachment/{id}/expand/raw": ("GET",),
    "/rest/api/3/comment/list": ("POST",),
    "/rest/api/3/comment/{commentId}/properties": ("GET",),
    "/rest/api/3/comment/{commentId}/properties/{propertyKey}": ("DELETE", "GET", "PUT"),
    "/rest/api/3/field": ("POST",),
    "/rest/api/3/issue/archive": ("POST", "PUT"),
    "/rest/api/3/issue/bulk": ("POST",),
    "/rest/api/3/issue/bulkfetch": ("POST",),
    "/rest/api/3/issue/createmeta": ("GET",),
    "/rest/api/3/issue/limit/adf/report": ("GET",),
    "/rest/api/3/issue/limit/report": ("GET",),
    "/rest/api/3/issue/picker": ("GET",),
    "/rest/api/3/issue/properties": ("POST",),
    "/rest/api/3/issue/properties/multi": ("POST",),
    "/rest/api/3/issue/properties/{propertyKey}": ("DELETE", "PUT"),
    "/rest/api/3/issue/unarchive": ("PUT",),
    "/rest/api/3/issue/watching": ("POST",),
    "/rest/api/3/issue/{issueIdOrKey}/attachments": ("POST",),
    "/rest/api/3/issue/{issueIdOrKey}/changelog/list": ("POST",),
    "/rest/api/3/issue/{issueIdOrKey}/comment/{id}": ("DELETE", "GET", "PUT"),
    "/rest/api/3/issue/{issueIdOrKey}/editmeta": ("GET",),
    "/rest/api/3/issue/{issueIdOrKey}/notify": ("POST",),
    "/rest/api/3/issue/{issueIdOrKey}/properties": ("GET",),
    "/rest/api/3/issue/{issueIdOrKey}/properties/{propertyKey}": ("DELETE", "GET", "PUT"),
    "/rest/api/3/issue/{issueIdOrKey}/remotelink": ("DELETE", "GET", "POST"),
    "/rest/api/3/issue/{issueIdOrKey}/remotelink/{linkId}": ("DELETE", "GET", "PUT"),
    "/rest/api/3/issue/{issueIdOrKey}/votes": ("DELETE", "GET", "POST"),
    "/rest/api/3/issue/{issueIdOrKey}/watchers": ("DELETE", "GET", "POST"),
    "/rest/api/3/issue/{issueIdOrKey}/worklog": ("DELETE", "GET", "POST"),
    "/rest/api/3/issue/{issueIdOrKey}/worklog/move": ("POST",),
    "/rest/api/3/issue/{issueIdOrKey}/worklog/{id}": ("DELETE", "GET", "PUT"),
    "/rest/api/3/issue/{issueIdOrKey}/worklog/{worklogId}/properties": ("GET",),
    "/rest/api/3/issue/{issueIdOrKey}/worklog/{worklogId}/properties/{propertyKey}": ("DELETE", "GET", "PUT"),
    "/rest/api/3/issueLinkType": ("POST",),
    "/rest/api/3/issueLinkType/{issueLinkTypeId}": ("DELETE", "GET", "PUT"),
    "/rest/api/3/issuetype": ("POST",),
    "/rest/api/3/issuetype/{id}": ("DELETE", "GET", "PUT"),
    "/rest/api/3/jql/autocompletedata": ("GET", "POST"),
    "/rest/api/3/jql/autocompletedata/suggestions": ("GET",),
    "/rest/api/3/jql/function/computation": ("GET", "POST"),
    "/rest/api/3/jql/function/computation/search": ("POST",),
    "/rest/api/3/jql/match": ("POST",),
    "/rest/api/3/jql/parse": ("POST",),
    "/rest/api/3/jql/pdcleaner": ("POST",),
    "/rest/api/3/jql/sanitize": ("POST",),
    "/rest/api/3/priority": ("POST",),
    "/rest/api/3/priority/{id}": ("DELETE", "GET", "PUT"),
    "/rest/api/3/project": ("GET",),
    "/rest/api/3/project/recent": ("GET",),
    "/rest/api/3/project/type": ("GET",),
    "/rest/api/3/project/type/accessible": ("GET",),
    "/rest/api/3/project/type/{projectTypeKey}": ("GET",),
    "/rest/api/3/project/type/{projectTypeKey}/accessible": ("GET",),
    "/rest/api/3/project/{projectIdOrKey}": ("DELETE", "PUT"),
    "/rest/api/3/project/{projectIdOrKey}/archive": ("POST",),
    "/rest/api/3/project/{projectIdOrKey}/avatar": ("PUT",),
    "/rest/api/3/project/{projectIdOrKey}/avatar/{id}": ("DELETE",),
    "/rest/api/3/project/{projectIdOrKey}/avatar2": ("POST",),
    "/rest/api/3/project/{projectIdOrKey}/avatars": ("GET",),
    "/rest/api/3/project/{projectIdOrKey}/classification-config": ("GET",),
    "/rest/api/3/project/{projectIdOrKey}/classification-level/default": ("DELETE", "GET", "PUT"),
    "/rest/api/3/project/{projectIdOrKey}/component": ("GET",),
    "/rest/api/3/project/{projectIdOrKey}/components": ("GET",),
    "/rest/api/3/project/{projectIdOrKey}/delete": ("POST",),
    "/rest/api/3/project/{projectIdOrKey}/features": ("GET",),
    "/rest/api/3/project/{projectIdOrKey}/features/{featureKey}": ("PUT",),
    "/rest/api/3/project/{projectIdOrKey}/properties": ("GET",),
    "/rest/api/3/project/{projectIdOrKey}/properties/{propertyKey}": ("DELETE", "GET", "PUT"),
    "/rest/api/3/project/{projectIdOrKey}/restore": ("POST",),
    "/rest/api/3/project/{projectIdOrKey}/role/{id}": ("DELETE", "PUT"),
    "/rest/api/3/project/{projectIdOrKey}/roledetails": ("GET",),
    "/rest/api/3/project/{projectIdOrKey}/version": ("GET",),
    "/rest/api/3/project/{projectIdOrKey}/versions": ("GET",),
    "/rest/api/3/project/{projectId}/email": ("GET", "PUT"),
    "/rest/api/3/project/{projectId}/hierarchy": ("GET",),
    "/rest/api/3/project/{projectKeyOrId}/issuesecuritylevelscheme": ("GET",),
    "/rest/api/3/project/{projectKeyOrId}/notificationscheme": ("GET",),
    "/rest/api/3/project/{projectKeyOrId}/permissionscheme": ("GET", "PUT"),
    "/rest/api/3/project/{projectKeyOrId}/securitylevel": ("GET",),
    "/rest/api/3/resolution": ("POST",),
    "/rest/api/3/resolution/{id}": ("DELETE", "GET", "PUT"),
    "/rest/api/3/status/{idOrName}": ("GET",),
    "/rest/api/3/statuscategory/{idOrKey}": ("GET",),
    "/rest/api/3/user": ("DELETE", "POST"),
    "/rest/api/3/user/assignable/multiProjectSearch": ("GET",),
    "/rest/api/3/user/bulk": ("GET",),
    "/rest/api/3/user/bulk/migration": ("GET",),
    "/rest/api/3/user/columns": ("DELETE", "GET", "PUT"),
    "/rest/api/3/user/email": ("GET",),
    "/rest/api/3/user/email/bulk": ("GET",),
    "/rest/api/3/user/groups": ("GET",),
    "/rest/api/3/user/permission/search": ("GET",),
    "/rest/api/3/user/picker": ("GET",),
    "/rest/api/3/user/properties": ("GET",),
    "/rest/api/3/user/properties/{propertyKey}": ("DELETE", "GET", "PUT"),
    "/rest/api/3/user/search/query": ("GET",),
    "/rest/api/3/user/search/query/key": ("GET",),
    "/rest/api/3/user/viewissue/search": ("GET",),
    "/rest/api/3/worklog/deleted": ("GET",),
    "/rest/api/3/worklog/list": ("POST",),
    "/rest/api/3/worklog/updated": ("GET",),
}
"""Each path template, in the vendor's own spelling, and the methods on it this fake refuses by name."""
