"""What the YouTrack provider claims. Data only: nothing else in the provider is imported to read it.

YouTrack Cloud serves its REST API at `/api/...` on `*.youtrack.cloud` and at
`/youtrack/api/...` on the older `*.myjetbrains.com` instances. One `path_prefix`
cannot say both, so the manifest strips nothing and the app answers both path
shapes itself, on either host family.
"""

from __future__ import annotations

from minutehand.domain.provider import (
    Holds,
    Manifest,
    Tier,
    WorldKey,
)
from minutehand.domain.world import EntityKind

MANIFEST = Manifest(
    key="youtrack",
    tier=Tier.FINISHED,
    hosts=["*.youtrack.cloud", "*.myjetbrains.com"],
    kinds=[EntityKind.TICKET, EntityKind.COMMENT],
    world_keys=[WorldKey(host="{key}.youtrack.cloud"), WorldKey(host="{key}.myjetbrains.com")],
    holds=Holds(
        person_without_email=True,
        person_title=False,
        person_guest=False,
        person_deactivated=True,
        person_bot=False,
        person_working_hours=False,
        person_absences=False,
        account_login=True,
        account_id=True,
        account_name=True,
        account_email_hidden=True,
        ticket_key=True,
        ticket_labels=True,
        ticket_comments=True,
        ticket_number=True,
        ticket_id=True,
        document_spreadsheet=False,
        document_presentation=False,
        document_file=False,
        document_folder=False,
        document_owner=False,
        document_space=False,
        document_shared_with=False,
        document_modified_before_start=False,
        document_modified_by=False,
        document_id=False,
        channel_named=False,
        channel_direct=False,
        channel_private=False,
        channel_archived=False,
        channel_topic=False,
        channel_purpose=False,
        channel_without_agent=False,
        channel_history=False,
        channel_threads=False,
        channel_files=False,
        channel_id=False,
        channel_post_id=False,
        space_spaces=False,
        space_id=False,
        ticket_action_moves=True,
        ticket_action_reassigns=True,
        ticket_action_comments=True,
        ticket_action_deletes=True,
        messaging_posts=False,
        messaging_edits=False,
        messaging_deletes=False,
        messaging_reacts=False,
        messaging_joins=False,
        messaging_adds_agent=False,
        messaging_opens_agent=False,
        messaging_commands=False,
        document_change_edited=False,
        document_change_renamed=False,
        document_change_moved=False,
        document_change_shared=False,
        document_change_trashed=False,
        document_change_commented=False,
        document_change_field_set=False,
        people_change_removed=False,
        people_change_deactivated=True,
        people_change_reactivated=True,
        sign_ins=False,
        faults=True,
    ),
)
