"""The operations of YouTrack's REST API, among the resources this fake claims, that it does not serve.

The claimed resources' operations are read from YouTrack's own OpenAPI description, which every instance publishes at
`/api/openapi.json` (JetBrains' public instance's, version 2026.3, fetched 2026-10-08; the subset is kept as
`tests/data/vendor_surface/youtrack.json`). Each operation below is answered 501 naming it, never a 404 that would
read as "no such resource". A path outside the claimed resources is answered 501 naming the path. A method the
description does not list for a path is YouTrack's 405.
"""

from __future__ import annotations

UNSERVED: tuple[tuple[str, str], ...] = (
    ("GET", "/activities"),
    ("GET", "/activities/{id}"),
    ("GET", "/activitiesPage"),
    ("GET", "/admin/customFieldSettings/bundles/build"),
    ("POST", "/admin/customFieldSettings/bundles/build"),
    ("DELETE", "/admin/customFieldSettings/bundles/build/{id}"),
    ("GET", "/admin/customFieldSettings/bundles/build/{id}"),
    ("POST", "/admin/customFieldSettings/bundles/build/{id}"),
    ("GET", "/admin/customFieldSettings/bundles/build/{id}/values"),
    ("POST", "/admin/customFieldSettings/bundles/build/{id}/values"),
    ("DELETE", "/admin/customFieldSettings/bundles/build/{id}/values/{buildBundleElementId}"),
    ("GET", "/admin/customFieldSettings/bundles/build/{id}/values/{buildBundleElementId}"),
    ("POST", "/admin/customFieldSettings/bundles/build/{id}/values/{buildBundleElementId}"),
    ("POST", "/admin/customFieldSettings/bundles/enum"),
    ("DELETE", "/admin/customFieldSettings/bundles/enum/{id}"),
    ("POST", "/admin/customFieldSettings/bundles/enum/{id}"),
    ("DELETE", "/admin/customFieldSettings/bundles/enum/{id}/values/{enumBundleElementId}"),
    ("GET", "/admin/customFieldSettings/bundles/enum/{id}/values/{enumBundleElementId}"),
    ("POST", "/admin/customFieldSettings/bundles/enum/{id}/values/{enumBundleElementId}"),
    ("GET", "/admin/customFieldSettings/bundles/ownedField"),
    ("POST", "/admin/customFieldSettings/bundles/ownedField"),
    ("DELETE", "/admin/customFieldSettings/bundles/ownedField/{id}"),
    ("GET", "/admin/customFieldSettings/bundles/ownedField/{id}"),
    ("POST", "/admin/customFieldSettings/bundles/ownedField/{id}"),
    ("GET", "/admin/customFieldSettings/bundles/ownedField/{id}/values"),
    ("POST", "/admin/customFieldSettings/bundles/ownedField/{id}/values"),
    ("DELETE", "/admin/customFieldSettings/bundles/ownedField/{id}/values/{ownedBundleElementId}"),
    ("GET", "/admin/customFieldSettings/bundles/ownedField/{id}/values/{ownedBundleElementId}"),
    ("POST", "/admin/customFieldSettings/bundles/ownedField/{id}/values/{ownedBundleElementId}"),
    ("POST", "/admin/customFieldSettings/bundles/state"),
    ("DELETE", "/admin/customFieldSettings/bundles/state/{id}"),
    ("POST", "/admin/customFieldSettings/bundles/state/{id}"),
    ("DELETE", "/admin/customFieldSettings/bundles/state/{id}/values/{stateBundleElementId}"),
    ("GET", "/admin/customFieldSettings/bundles/state/{id}/values/{stateBundleElementId}"),
    ("POST", "/admin/customFieldSettings/bundles/state/{id}/values/{stateBundleElementId}"),
    ("POST", "/admin/customFieldSettings/bundles/user"),
    ("DELETE", "/admin/customFieldSettings/bundles/user/{id}"),
    ("POST", "/admin/customFieldSettings/bundles/user/{id}"),
    ("GET", "/admin/customFieldSettings/bundles/user/{id}/aggregatedUsers"),
    ("GET", "/admin/customFieldSettings/bundles/user/{id}/groups"),
    ("POST", "/admin/customFieldSettings/bundles/user/{id}/groups"),
    ("DELETE", "/admin/customFieldSettings/bundles/user/{id}/groups/{userGroupId}"),
    ("GET", "/admin/customFieldSettings/bundles/user/{id}/groups/{userGroupId}"),
    ("GET", "/admin/customFieldSettings/bundles/user/{id}/individuals"),
    ("POST", "/admin/customFieldSettings/bundles/user/{id}/individuals"),
    ("DELETE", "/admin/customFieldSettings/bundles/user/{id}/individuals/{userId}"),
    ("GET", "/admin/customFieldSettings/bundles/user/{id}/individuals/{userId}"),
    ("POST", "/admin/customFieldSettings/bundles/version"),
    ("DELETE", "/admin/customFieldSettings/bundles/version/{id}"),
    ("POST", "/admin/customFieldSettings/bundles/version/{id}"),
    ("DELETE", "/admin/customFieldSettings/bundles/version/{id}/values/{versionBundleElementId}"),
    ("GET", "/admin/customFieldSettings/bundles/version/{id}/values/{versionBundleElementId}"),
    ("POST", "/admin/customFieldSettings/bundles/version/{id}/values/{versionBundleElementId}"),
    ("DELETE", "/admin/customFieldSettings/customFields/{id}"),
    ("POST", "/admin/customFieldSettings/customFields/{id}"),
    ("GET", "/admin/customFieldSettings/customFields/{id}/fieldDefaults"),
    ("POST", "/admin/customFieldSettings/customFields/{id}/fieldDefaults"),
    ("GET", "/admin/customFieldSettings/customFields/{id}/instances"),
    ("GET", "/admin/customFieldSettings/types"),
    ("DELETE", "/admin/projects/{id}"),
    ("POST", "/admin/projects/{id}"),
    ("GET", "/admin/projects/{id}/articles"),
    ("DELETE", "/admin/projects/{id}/customFields/{projectCustomFieldId}"),
    ("POST", "/admin/projects/{id}/customFields/{projectCustomFieldId}"),
    ("GET", "/admin/projects/{id}/issues"),
    ("POST", "/admin/projects/{id}/issues"),
    ("DELETE", "/admin/projects/{id}/issues/{issueId}"),
    ("GET", "/admin/projects/{id}/issues/{issueId}"),
    ("POST", "/admin/projects/{id}/issues/{issueId}"),
    ("POST", "/admin/projects/{id}/team"),
    ("GET", "/admin/projects/{id}/team/groups"),
    ("POST", "/admin/projects/{id}/team/groups"),
    ("DELETE", "/admin/projects/{id}/team/groups/{userGroupId}"),
    ("GET", "/admin/projects/{id}/team/ownUsers"),
    ("DELETE", "/admin/projects/{id}/team/ownUsers/{userId}"),
    ("GET", "/admin/projects/{id}/timeTrackingSettings"),
    ("POST", "/admin/projects/{id}/timeTrackingSettings"),
    ("GET", "/admin/projects/{id}/timeTrackingSettings/workItemTypes"),
    ("POST", "/admin/projects/{id}/timeTrackingSettings/workItemTypes"),
    ("DELETE", "/admin/projects/{id}/timeTrackingSettings/workItemTypes/{workItemTypeId}"),
    ("GET", "/admin/projects/{id}/timeTrackingSettings/workItemTypes/{workItemTypeId}"),
    ("POST", "/commands/assist"),
    ("POST", "/issueLinkTypes"),
    ("DELETE", "/issueLinkTypes/{id}"),
    ("GET", "/issueLinkTypes/{id}"),
    ("POST", "/issueLinkTypes/{id}"),
    ("GET", "/issues/{id}/activities/{activityItemId}"),
    ("GET", "/issues/{id}/activitiesPage"),
    ("GET", "/issues/{id}/attachments"),
    ("POST", "/issues/{id}/attachments"),
    ("DELETE", "/issues/{id}/attachments/{issueAttachmentId}"),
    ("GET", "/issues/{id}/attachments/{issueAttachmentId}"),
    ("POST", "/issues/{id}/attachments/{issueAttachmentId}"),
    ("DELETE", "/issues/{id}/comments/{issueCommentId}"),
    ("POST", "/issues/{id}/comments/{issueCommentId}"),
    ("GET", "/issues/{id}/comments/{issueCommentId}/reactions"),
    ("POST", "/issues/{id}/comments/{issueCommentId}/reactions"),
    ("DELETE", "/issues/{id}/comments/{issueCommentId}/reactions/{reactionId}"),
    ("GET", "/issues/{id}/comments/{issueCommentId}/reactions/{reactionId}"),
    ("GET", "/issues/{id}/project"),
    ("POST", "/issues/{id}/project"),
    ("GET", "/issues/{id}/sprints"),
    ("GET", "/issues/{id}/tags/{tagId}"),
    ("GET", "/issues/{id}/timeTracking"),
    ("GET", "/issues/{id}/timeTracking/workItems"),
    ("POST", "/issues/{id}/timeTracking/workItems"),
    ("DELETE", "/issues/{id}/timeTracking/workItems/{issueWorkItemId}"),
    ("GET", "/issues/{id}/timeTracking/workItems/{issueWorkItemId}"),
    ("POST", "/issues/{id}/timeTracking/workItems/{issueWorkItemId}"),
    ("GET", "/issues/{id}/vcsChanges"),
    ("POST", "/issues/{id}/vcsChanges"),
    ("DELETE", "/issues/{id}/vcsChanges/{vcsChangeId}"),
    ("GET", "/issues/{id}/vcsChanges/{vcsChangeId}"),
    ("POST", "/issues/{id}/vcsChanges/{vcsChangeId}"),
    ("DELETE", "/tags/{id}"),
    ("POST", "/tags/{id}"),
    ("GET", "/tags/{id}/issues"),
    ("POST", "/users"),
    ("POST", "/users/{id}"),
    ("GET", "/users/{id}/profiles/general"),
    ("POST", "/users/{id}/profiles/general"),
    ("GET", "/users/{id}/profiles/notifications"),
    ("POST", "/users/{id}/profiles/notifications"),
    ("GET", "/users/{id}/profiles/timetracking"),
    ("POST", "/users/{id}/profiles/timetracking"),
    ("GET", "/users/{id}/savedQueries"),
    ("GET", "/users/{id}/tags"),
    ("GET", "/workItems"),
    ("GET", "/workItems/{id}"),
)
"""Each `(method, path)` in YouTrack's own spelling of the path template."""
